name: PHPUNIT

on:
  push:
    branches:
      - main
      - '*.x'

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        env:
          TEST_NAME: Twipsi
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 0
          memory_limit: 1600M
