name: PHPUNIT

on:
  push:
    branches:
      - main
      - '*.x'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1 ]
        stability: [ prefer-stable ]
        include:
          - php: 8.2
            stability: prefer-stable --ignore-platform-req=php+

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_sqlite, gd, gmp
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Run unit Tests
        run: vendor/bin/phpunit --verbose
        env:
          TEST_NAME: Twipsi
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 0
          memory_limit: 1600M
